export const pathDefault = {
  homePage: "/",
  register: "/sign-up",
  login: "/sign-in",
  listJob: "/list-job",
  adminTemplate: "/admin",
  adminLogin: "/admin-login",
  managerUser: "manager-user",
  createUser: "create-user",
  lookingToHire: "looking-to-hire",
  proService: "pro-services",
  listJobsPage: "/list-jobs-page",
  detail: "/cong-viec-chi-tiet",
  profileuser: "/profile-user",
  jobManagement: "job-management",
  uploadAdmin: "upload-admin",
  commentManagement: "comment-management",
  becomeASeller: "become-a-seller",
  listTypeJobs: "/list-type-jobs",
};
